# Generated by Django 5.0.7 on 2025-02-01 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_schedule_task_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed')], default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
