# Generated by Django 5.0.7 on 2025-02-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end_time',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_time',
            field=models.CharField(max_length=10),
        ),
    ]
